# Diabetes Risk Prediction

## 02 - Data Preprocessing

### Objectives

This notebook prepares the raw dataset for downstream statistical analysis and machine learning by:

- Converting variables to appropriate data types
- Creating clinically meaningful categorical variables
- Assessing data quality
- Saving the processed dataset

### Input

data/raw/diabetes_raw.csv

### Output

data/processed/diabetes_processed.csv

In [1]:
# ===============================================================
# Import Libraries
# ===============================================================

from pathlib import Path

import numpy as np
import pandas as pd

In [2]:
# ===============================================================
# Project Configuration
# ===============================================================

PROJECT_ROOT = Path.cwd().parent

DATA_DIR = PROJECT_ROOT / "data"

RAW_DATA_DIR = DATA_DIR / "raw"

PROCESSED_DATA_DIR = DATA_DIR / "processed"

RESULTS_DIR = PROJECT_ROOT / "results"

PROCESSED_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)

RESULTS_DIR.mkdir(
    parents=True,
    exist_ok=True
)

In [3]:
# ===============================================================
# Load Raw Dataset
# ===============================================================

raw_data_path = RAW_DATA_DIR / "diabetes_raw.csv"

df = pd.read_csv(raw_data_path)

print(f"Dataset Shape: {df.shape}")

display(df.head())

Dataset Shape: (253680, 22)

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,Diabetes_binary
0,1,1,1,40,1,0,0,0,0,1,...,0,5,18,15,1,0,9,4,3,0
1,0,0,0,25,1,0,0,1,0,0,...,1,3,0,0,0,0,7,6,1,0
2,1,1,1,28,0,0,0,0,1,0,...,1,5,30,30,1,0,9,4,8,0
3,1,0,1,27,0,0,0,1,1,1,...,0,2,0,0,0,0,11,3,6,0
4,1,1,1,24,0,0,0,1,1,1,...,0,2,3,0,0,0,11,5,4,0

In [4]:
# ===============================================================
# Initial Data Inspection
# ===============================================================

print("=" * 80)
print("Dataset Information")
print("=" * 80)

df.info()

print("\n")

print("=" * 80)
print("Summary Statistics")
print("=" * 80)

display(df.describe(include="all"))

================================================================================
Dataset Information
================================================================================
<class 'pandas.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   HighBP                253680 non-null  int64
 1   HighChol              253680 non-null  int64
 2   CholCheck             253680 non-null  int64
 3   BMI                   253680 non-null  int64
 4   Smoker                253680 non-null  int64
 5   Stroke                253680 non-null  int64
 6   HeartDiseaseorAttack  253680 non-null  int64
 7   PhysActivity          253680 non-null  int64
 8   Fruits                253680 non-null  int64
 9   Veggies               253680 non-null  int64
 10  HvyAlcoholConsump     253680 non-null  int64
 11  AnyHealthcare         253680 non-null  int64
 12  NoDocbcCost           253680 non-null  int64
 13  GenHlth               253680 non-null  int64
 14  MentHlth              253680 non-null  int64
 15  PhysHlth              253680 non-null  int64
 16  DiffWalk              253680 non-null  int64
 17  Sex                   253680 non-null  int64
 18  Age                   253680 non-null  int64
 19  Education             253680 non-null  int64
 20  Income                253680 non-null  int64
 21  Diabetes_binary       253680 non-null  int64
dtypes: int64(22)
memory usage: 42.6 MB


================================================================================
Summary Statistics
================================================================================

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income,Diabetes_binary
count,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,...,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000,253680.000000
mean,0.429001,0.424121,0.962670,28.382364,0.443169,0.040571,0.094186,0.756544,0.634256,0.811420,...,0.084177,2.511392,3.184772,4.242081,0.168224,0.440342,8.032119,5.050434,6.053875,0.139333
std,0.494934,0.494210,0.189571,6.608694,0.496761,0.197294,0.292087,0.429169,0.481639,0.391175,...,0.277654,1.068477,7.412847,8.717951,0.374066,0.496429,3.054220,0.985774,2.071148,0.346294
min,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,0.000000,0.000000,1.000000,24.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,...,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,6.000000,4.000000,5.000000,0.000000
50%,0.000000,0.000000,1.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,...,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,8.000000,5.000000,7.000000,0.000000
75%,1.000000,1.000000,1.000000,31.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,...,0.000000,3.000000,2.000000,3.000000,0.000000,1.000000,10.000000,6.000000,8.000000,0.000000
max,1.000000,1.000000,1.000000,98.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,5.000000,30.000000,30.000000,1.000000,1.000000,13.000000,6.000000,8.000000,1.000000

In [5]:
# ===============================================================
# Convert Data Types
# ===============================================================

categorical_columns = [

    "Diabetes_binary",

    "HighBP",

    "HighChol",

    "Smoker",

    "Stroke",

    "HeartDiseaseorAttack",

    "PhysActivity",

    "Fruits",

    "Veggies",

    "HvyAlcoholConsump",

    "AnyHealthcare",

    "NoDocbcCost",

    "GenHlth",

    "MentHlth",

    "PhysHlth",

    "DiffWalk",

    "Sex",

    "Education",

    "Income",

    "CholCheck",

    "Age"

]

df[categorical_columns] = (

    df[categorical_columns]

    .astype("category")

)

print(df.dtypes)

HighBP                  category
HighChol                category
CholCheck               category
BMI                        int64
Smoker                  category
Stroke                  category
HeartDiseaseorAttack    category
PhysActivity            category
Fruits                  category
Veggies                 category
HvyAlcoholConsump       category
AnyHealthcare           category
NoDocbcCost             category
GenHlth                 category
MentHlth                category
PhysHlth                category
DiffWalk                category
Sex                     category
Age                     category
Education               category
Income                  category
Diabetes_binary         category
dtype: object

In [6]:
# ===============================================================
# Create BMI Categories
# ===============================================================

bmi_bins = [

    -np.inf,

    18.5,

    25,

    30,

    np.inf

]

bmi_labels = [

    "Underweight",

    "Normal weight",

    "Overweight",

    "Obese"

]

df["BMI_cat"] = pd.cut(

    df["BMI"],

    bins=bmi_bins,

    labels=bmi_labels,

    ordered=True

)

In [7]:
# ===============================================================
# Create Mental Health Categories
# ===============================================================

df["MentHlth_cat"] = pd.cut(

    df["MentHlth"],

    bins=[-1, 0, 10, 20, 30],

    labels=[

        "0 days",

        "1-10 days",

        "11-20 days",

        "21-30 days"

    ]

)

In [8]:
# ===============================================================
# Create Physical Health Categories
# ===============================================================

df["PhysHlth_cat"] = pd.cut(

    df["PhysHlth"],

    bins=[-1, 0, 10, 20, 30],

    labels=[

        "0 days",

        "1-10 days",

        "11-20 days",

        "21-30 days"

    ]

)

In [9]:
# ===============================================================
# Data Quality Assessment
# ===============================================================

print("=" * 80)
print("Data Quality Assessment")
print("=" * 80)

print(f"Observations : {df.shape[0]}")

print(f"Variables    : {df.shape[1]}")

print(f"Duplicates   : {df.duplicated().sum()}")

print("\n")

print("Missing Values")

display(df.isnull().sum())

print("\n")

print("Data Types")

display(df.dtypes)

================================================================================
Data Quality Assessment
================================================================================
Observations : 253680
Variables    : 25
Duplicates   : 24206


Missing Values

HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
HeartDiseaseorAttack    0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
Diabetes_binary         0
BMI_cat                 0
MentHlth_cat            0
PhysHlth_cat            0
dtype: int64

Data Types

HighBP                  category
HighChol                category
CholCheck               category
BMI                        int64
Smoker                  category
Stroke                  category
HeartDiseaseorAttack    category
PhysActivity            category
Fruits                  category
Veggies                 category
HvyAlcoholConsump       category
AnyHealthcare           category
NoDocbcCost             category
GenHlth                 category
MentHlth                category
PhysHlth                category
DiffWalk                category
Sex                     category
Age                     category
Education               category
Income                  category
Diabetes_binary         category
BMI_cat                 category
MentHlth_cat            category
PhysHlth_cat            category
dtype: object

In [10]:
# ===============================================================
# Save Processed Dataset
# ===============================================================

processed_path = (

    PROCESSED_DATA_DIR

    / "diabetes_processed.csv"

)

df.to_csv(

    processed_path,

    index=False

)

print(f"Processed dataset saved to:\n{processed_path}")

Processed dataset saved to:
c:\Users\saifu\OneDrive\Documents\Python_Demo\Diabetes-Risk-Prediction\data\processed\diabetes_processed.csv

In [11]:
# ===============================================================
# Verify Saved Dataset
# ===============================================================

print("=" * 80)

print("Processed Dataset")

print("=" * 80)

print(df.head())

print("\n")

print(df.info())

================================================================================
Processed Dataset
================================================================================
  HighBP HighChol CholCheck  BMI Smoker Stroke HeartDiseaseorAttack  \
0      1        1         1   40      1      0                    0
1      0        0         0   25      1      0                    0
2      1        1         1   28      0      0                    0
3      1        0         1   27      0      0                    0
4      1        1         1   24      0      0                    0

  PhysActivity Fruits Veggies  ... PhysHlth DiffWalk Sex Age Education Income  \
0            0      0       1  ...       15        1   0   9         4      3
1            1      0       0  ...        0        0   0   7         6      1
2            0      1       0  ...       30        1   0   9         4      8
3            1      1       1  ...        0        0   0  11         3      6
4            1      1       1  ...        0        0   0  11         5      4

  Diabetes_binary        BMI_cat MentHlth_cat PhysHlth_cat
0               0          Obese   11-20 days   11-20 days
1               0  Normal weight       0 days       0 days
2               0     Overweight   21-30 days   21-30 days
3               0     Overweight       0 days       0 days
4               0  Normal weight    1-10 days       0 days

[5 rows x 25 columns]


<class 'pandas.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 25 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   HighBP                253680 non-null  category
 1   HighChol              253680 non-null  category
 2   CholCheck             253680 non-null  category
 3   BMI                   253680 non-null  int64
 4   Smoker                253680 non-null  category
 5   Stroke                253680 non-null  category
 6   HeartDiseaseorAttack  253680 non-null  category
 7   PhysActivity          253680 non-null  category
 8   Fruits                253680 non-null  category
 9   Veggies               253680 non-null  category
 10  HvyAlcoholConsump     253680 non-null  category
 11  AnyHealthcare         253680 non-null  category
 12  NoDocbcCost           253680 non-null  category
 13  GenHlth               253680 non-null  category
 14  MentHlth              253680 non-null  category
 15  PhysHlth              253680 non-null  category
 16  DiffWalk              253680 non-null  category
 17  Sex                   253680 non-null  category
 18  Age                   253680 non-null  category
 19  Education             253680 non-null  category
 20  Income                253680 non-null  category
 21  Diabetes_binary       253680 non-null  category
 22  BMI_cat               253680 non-null  category
 23  MentHlth_cat          253680 non-null  category
 24  PhysHlth_cat          253680 non-null  category
dtypes: category(24), int64(1)
memory usage: 7.7 MB
None